using System.Collections.Generic;

namespace Phone_T9
{
    public class WordList
    {
        public HashSet<string> commonWords = new HashSet<string>()
        {
            "the", "be", "to", "of", "and", "a", "in", "that", "have", "I",
            "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
            "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
            "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
            "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
            "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
            "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
            "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
            "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
            "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
            "are", "had", "has", "make", "work", "could", "year", "all", "down", "there",
            "only", "take", "long", "use", "said", "was", "after", "think", "your", "way",
            "find", "use", "just", "think", "make", "see", "time", "which", "will", "way",
            "also", "play", "than", "two", "other", "time", "look", "more", "write", "go",
            "see", "number", "no", "way", "could", "people", "my", "than", "first", "water",
            "been", "call", "who", "oil", "its", "now", "find", "long", "down", "day",
            "did", "get", "come", "made", "may", "part", "over", "hand", "own", "way",
            "does", "even", "place", "because", "often", "may", "ask", "live", "most", "because",
            "year", "my", "and", "of", "know", "came", "run", "new", "us", "show",
            "like", "under", "has", "play", "men", "was", "change", "house", "off", "need",
            "try", "kind", "hand", "start", "such", "side", "should", "why", "last", "much",
            "mean", "big", "old", "case", "same", "tell", "set", "seem", "help", "every",
            "ask", "right", "study", "often", "stand", "place", "such", "set", "own", "both",
            "come", "answer", "make", "turn", "long", "she", "him", "try", "even", "again",
            "must", "much", "last", "send", "different", "down", "once", "run", "try", "small",
            "use", "before", "call", "move", "old", "well", "even", "too", "same", "tell",
            "set", "seem", "want", "she", "last", "off", "give", "head", "good", "high",
            "number", "add", "often", "important", "play", "own", "far", "last", "ask", "found",
            "school", "no", "help", "two", "mother", "tell", "he", "earth", "last", "father",
            "miss", "point", "leave", "let", "near", "might", "keep", "between", "under", "life",
            "year", "follow", "hold", "went", "mother", "know", "since", "cut", "new", "where",
            "few", "state", "very", "round", "live", "me", "child", "next", "side", "father",
            "both", "until", "group", "start", "often", "run", "important", "stop", "even", "same",
            "show", "set", "often", "begin", "seem", "long", "own", "both", "play", "off",
            "always", "night", "never", "next", "how", "give", "said", "look", "when", "should",
            "find", "child", "study", "start", "still", "use", "need", "like", "many", "word",
            "near", "line", "turn", "next", "work", "feel", "might", "play", "most", "ask",
            "find", "here", "put", "often", "back", "run", "does", "again", "show", "great",
            "off", "high", "must", "such", "own", "set", "off", "head", "play", "number",
            "one", "both", "small", "such", "head", "follow", "much", "try", "last", "leave",
            "low", "even", "first", "try", "first", "more", "find", "state", "good", "next",
            "all", "make", "good", "high", "long", "even", "own", "left", "off", "do",
            "must", "left", "two", "high", "follow", "together", "does", "most", "try", "again",
            "hear", "small", "left", "two", "second", "away", "second", "set", "seem", "head",
            "point", "how", "like", "take", "next", "world", "place", "set", "together", "put",
            "change", "state", "may", "far", "hand", "tell", "hear", "same", "between", "end",
            "run", "try", "went", "every", "want", "long", "something", "much", "left", "try",
            "head", "make", "still", "point", "near", "here", "live", "follow", "ask", "earth",
            "off", "why", "may", "must", "end", "even", "leave", "must", "small", "mean",
            "leave", "line", "hand", "long", "great", "group", "left", "play", "why", "run",
            "line", "play", "here", "leave", "both", "my", "went", "may", "does", "such",
            "show", "here", "two", "play", "long", "often", "three", "does", "run", "same",
            "even", "small", "try", "three", "hand", "after", "stop", "tell", "even", "tell",
            "could", "still", "near", "leave", "take", "my", "often", "under", "kind", "world",
            "feel", "near", "does", "left", "use", "until", "off", "place", "high", "even",
            "life", "own", "kind", "under", "far", "again", "must", "school", "must", "right",
            "word", "left", "even", "leave", "line", "how", "often", "does", "both", "even",
            "where", "do", "say", "must", "even", "does", "back", "why", "such", "kind",
            "point", "off", "even", "do", "long", "same", "thing", "place", "from", "even",
            "live", "line", "always", "take", "what", "such", "high", "great", "may", "my",
            "may", "place", "group", "ask", "after", "head", "first", "from", "even", "same",
            "end", "hand", "place", "first", "even", "small", "leave", "stop", "under", "line",
            "even", "must", "high", "next", "thing", "tell", "three", "play", "great", "even",
            "leave", "do", "how", "line", "good", "feel", "even", "group", "find", "how",
            "does", "how", "high", "live", "still", "right", "great", "must",
        };
    }
}
